#!/usr/bin/env python3
"""Generate IMX678 sensor-config variants from the LI baseline by register override.

This is the "own the driver" generator: rather than hand-editing 900-line XMLs, it takes
the LI baseline `cmk_imx678_sensor.xml` and stamps out variants that differ only in named
sensor registers (conversion gain, analog gain, exposure, frame length). Each variant is a
complete sensor XML ready for the QTI ParameterParser (see compile.sh).

We build these ourselves end-to-end (ParameterParser is local in the QLI 1.7 toolchain), so
this does NOT depend on hvo / Leopard / a build host.

Register facts (verified from the baseline, IMX678 datasheet, SW ref):
  FDG_SEL0 0x3030[1:0]  conversion gain: 0x00=LCG, 0x01=HCG
  GAIN     0x3070       analog gain, 0.3 dB/step (reg = round(dB/0.3)), 0..0xF0 = 0..72 dB
  SHR0     0x3050..52   shutter (little-endian 3 bytes); integ_lines = VMAX - SHR0
  VMAX     0x3028..2A   frame length (little-endian 3 bytes); fps = 1/(VMAX * t_line)
  t_line   = 14.815 us (4-lane, 900 MHz out-clk, HMAX=1100); baseline: VMAX=2250, SHR0=900 -> 20 ms

Usage:  python build_variants.py            # generate all enabled variants + the buildbins yaml
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BASELINE = os.path.join(HERE, "baseline", "cmk_imx678_sensor.xml")
MODULE_XML = "module/cmk_imx678_module_cam0.xml"   # shared, unchanged, path relative to oem/qcom
OUTDIR = os.path.join(HERE, "generated")

# ---- timing / gain helpers (so ladders are expressed in real units) ---------
T_LINE_US = 14.815
VMAX_BASE = 2250


def le3(value):
    """Return three (addr,data) byte pairs for a little-endian 20-bit reg trio at base addr."""
    return [(value >> 0) & 0xFF, (value >> 8) & 0xFF, (value >> 16) & 0xFF]


def gain_db(db):
    """GAIN register override for an analog gain in dB (0.3 dB/step)."""
    reg = max(0, min(0xF0, round(db / 0.3)))
    return [("0x3070", "0x%02X" % reg)]


def shr0_ms(t_ms, vmax=VMAX_BASE):
    """SHR0 (0x3050..52) override for an exposure time in ms at the given VMAX."""
    integ = int(round(t_ms * 1000.0 / T_LINE_US))
    shr0 = max(1, vmax - integ)
    lo, mid, hi = le3(shr0)
    return [("0x3050", "0x%02X" % lo), ("0x3051", "0x%02X" % mid), ("0x3052", "0x%02X" % hi)]


# ---- variant manifest --------------------------------------------------------
# Each: name (-> com.qti.sensormodule.<name>.bin), description, list of (regAddr, regData) overrides.
# Group 1 (conversion gain) is the FIRST build — it gives the DCG/Clear-HDR ratio K_LCG/K_HCG.
# Group 2 (gain ladder, LCG) anchors PTC/SNR vs analog gain. All are no-SRM (baseline-derived).
VARIANTS = [
    # --- conversion-gain pair (build these first: DCG-ratio + low-light noise floor) ---
    {"name": "cmk_imx678_cam0",       "desc": "LCG linear, 6 dB, 20 ms (baseline / reference)", "ov": []},
    {"name": "cmk_imx678_cam0_hcg",   "desc": "HCG linear (FDG_SEL0=1), 6 dB, 20 ms",           "ov": [("0x3030", "0x01")]},
    # --- analog-gain ladder at LCG (PTC / SNR-vs-gain) ---
    {"name": "cmk_imx678_cam0_g0",    "desc": "LCG linear, 0 dB",   "ov": gain_db(0)},
    {"name": "cmk_imx678_cam0_g12",   "desc": "LCG linear, 12 dB",  "ov": gain_db(12)},
    {"name": "cmk_imx678_cam0_g24",   "desc": "LCG linear, 24 dB",  "ov": gain_db(24)},
    # --- exposure examples (dark-current vs read-noise) — enable as needed ---
    # {"name": "cmk_imx678_cam0_e5",  "desc": "LCG linear, 5 ms",   "ov": shr0_ms(5)},
    # {"name": "cmk_imx678_cam0_e1",  "desc": "LCG linear, 1 ms",   "ov": shr0_ms(1)},
]

# Match one full <regSetting> ... </regSetting> and capture its data field, for a given addr.
def _apply(xml, addr, data):
    pat = re.compile(
        r"(<registerAddr>" + re.escape(addr) + r"</registerAddr><registerData>)0x[0-9A-Fa-f]+(</registerData>)")
    new, n = pat.subn(r"\g<1>" + data + r"\g<2>", xml)
    return new, n


def main():
    if not os.path.exists(BASELINE):
        sys.exit("baseline not found: %s" % BASELINE)
    with open(BASELINE, encoding="utf-8") as f:
        base = f.read()
    os.makedirs(OUTDIR, exist_ok=True)

    yaml_lines = ["# Auto-generated by build_variants.py — feed to buildbins.py (see compile.sh)",
                  "sensor_drivers:"]
    print("%-26s %-42s %s" % ("VARIANT", "DESCRIPTION", "OVERRIDES (verified)"))
    print("-" * 100)
    ok = True
    for v in VARIANTS:
        xml = base
        applied = []
        for addr, data in v["ov"]:
            xml, n = _apply(xml, addr, data)
            if n != 1:
                print("  !! %s: expected exactly 1 regSetting for %s, matched %d" % (v["name"], addr, n))
                ok = False
            applied.append("%s=%s" % (addr, data))
        # verify the write actually landed
        for addr, data in v["ov"]:
            if ("<registerAddr>%s</registerAddr><registerData>%s</registerData>" % (addr, data)) not in xml:
                print("  !! %s: verification failed for %s=%s" % (v["name"], addr, data))
                ok = False
        outname = v["name"] + "_sensor.xml"
        with open(os.path.join(OUTDIR, outname), "w", encoding="utf-8", newline="\n") as f:
            f.write(xml)
        yaml_lines += ["- com.qti.sensormodule.%s:" % v["name"],
                       "    - sensor/cmk_imx678/%s" % outname,
                       "    - %s" % MODULE_XML]
        print("%-26s %-42s %s" % (v["name"], v["desc"], ", ".join(applied) or "(identity)"))

    with open(os.path.join(OUTDIR, "buildbins_metro.yaml"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(yaml_lines) + "\n")
    print("-" * 100)
    print("wrote %d sensor XMLs + buildbins_metro.yaml to %s" % (len(VARIANTS), OUTDIR))
    print("next: ./compile.sh   (stages XMLs into the chi-cdk tree, runs ParameterParser -> .bin)")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
